### ISSUE TITLE
new initscript makes multi-instance complex

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/slapd-cli#10]
For example, for initscript, one must do:
- in `/etc/init.d/slapd`:
```
CLI_BIN="/var/ldap/server/sbin/$( basename $0 )-cli"
```
- create a symlink  `/etc/init.d/slapd-proxy`
- create a symlink  `/usr/local/openldap/sbin/slapd-cli-proxy`
- duplicate configuration `/usr/local/openldap/etc/openldap/slapd-proxy-cli.conf`

Maybe we could integrate first point directly in the code?

For systemd script, one must find a way to load dynamically the appropriate cli...

**Comment by coudot** [comment]
I updated doc here: https://ltb-project.org/documentation/openldap-initscript#run_several_openldap_instances

For me it is not so complex

**Comment by davidcoutadeur** [comment]
It is not so complex... It is just more complex than before.
Anyway, I don't see any other way to manage it...
Maybe documentation is sufficient enough indeed.
Thanks for the pointer, maybe we could close this issue unless you have other ideas for next 2.5 version.

**Comment by davidcoutadeur** [comment]
I think we can close this issue

**Comment by davidcoutadeur** [comment]
Seems there is no better way to deal with multi-instances
