### ISSUE TITLE
checksync target should not rely on slapcat + add a tolerance for contextCSN comparison

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/slapd-cli#11]
When computing synchronization checks, the checksync target relies on a slapcat to retrieve local contextCSN.
It is working as intended when making adds, but when making a delete, the contextCSN is only updated in memory, and not visible through a slapcat command.

Suggestion: use a ldapsearch to retrieve up-to-date contextCSN.

**Comment by coudot** [comment]
Maybe in OpenLDAP 2.5 it would be easier to check sync status in cn=monitor

**Comment by davidcoutadeur** [comment]
It seems OpenLDAP 2.5 does not have any new feature in cn=monitor to check syncrepl status.

Using ldapsearch means having credentials for every provider stored in `slapd-cli.conf`, which is not so desirable...

I suggest not to improve this feature for now.

**Comment by davidcoutadeur** [comment]
Here is the piece of cn=monitor describing the synchronization:

ldapsearch -Y EXTERNAL -H 'ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi' -b "cn=monitor" \* + -LLL > /tmp/monitor.ldif

```
dn: cn=Consumer 001,cn=Database 1,cn=Databases,cn=Monitor
objectClass: olmSyncReplInstance
structuralObjectClass: olmSyncReplInstance
cn: Consumer 001
creatorsName: cn=monitor
modifiersName: cn=monitor
createTimestamp: 20210908075111Z
modifyTimestamp: 20210908075111Z
olmSRProviderURIList: ldap://localhost:3390
olmSRConnection:
olmSRSyncPhase: Refresh
olmSRNextConnect: 20210908082614Z
olmSRLastConnect: 20210908082514Z
olmSRLastContact: 00000101000000Z
olmSRLastCookieRcvd:
olmSRLastCookieSent:
entryDN: cn=Consumer 001,cn=Database 1,cn=Databases,cn=Monitor
subschemaSubentry: cn=Subschema
hasSubordinates: FALSE

dn: cn=Consumer 000,cn=Database 1,cn=Databases,cn=Monitor
objectClass: olmSyncReplInstance
structuralObjectClass: olmSyncReplInstance
cn: Consumer 000
creatorsName: cn=monitor
modifiersName: cn=monitor
createTimestamp: 20210908075111Z
modifyTimestamp: 20210908075111Z
olmSRProviderURIList: ldap://localhost:3389
olmSRConnection: IP=127.0.0.1:40908
olmSRSyncPhase: Persist
olmSRNextConnect: 00000101000000Z
olmSRLastConnect: 20210908075211Z
olmSRLastContact: 20210908082522Z
olmSRLastCookieRcvd: rid=000,csn=20210908082522.652290Z#000000#000#000000
olmSRLastCookieSent: rid=000,sid=000,csn=20210907161949.876119Z#000000#000#000
 000
entryDN: cn=Consumer 000,cn=Database 1,cn=Databases,cn=Monitor
subschemaSubentry: cn=Subschema
hasSubordinates: FALSE
```

There is no documentation associated to these attributes, but here is my interpretation:
* **olmSRNextConnect**: 1 day + 1 month? May be used in another context than refresh and persist
* **olmSRLastConnect**: last time the consumer has established a connection to the provider
* **olmSRLastContact**: last time the consumer has contacted the provider
* **olmSRLastCookieRcvd**: last contextCSN reveived from the provider. This is the really usefull information here. However, it is empty at server startup, so we can't rely on it for synchronization status
* **olmSRLastCookieSent**: supposition: as this consumer is also a provider, this could be the last contextCSN stored

Conclusion:
It does not seem to be a good way to get the syncrepl status with cn=monitor.

I am going to ask the OpenLDAP dev team for their opinion.

**Comment by davidcoutadeur** [comment]
For the record, here is the answer of the community:

On Wed, Sep 08, 2021 at 11:30:57AM +0200, David Coutadeur wrote:
> Hi,
>
> I am trying to get the synchronization status of a given consumer for each
> of his declared provider.
>
> Synchronization status = Is this provider synchronized with the current
> consumer? (TRUE / FALSE)
>
> Currently, I can do that by comparing contextCSN stored into consumers and
> providers.
>
> I have noted that in OpenLDAP 2.5 there are new piece of information into
> cn=monitor:
> 1/ I haven't found any documentation about these attributes in OpenLDAP
> manual. Is there something in progress ?

There is no documentation on any of this yet. Feel free to write
something up for the admin guide, perhaps?

> 2/ if I understand correctly the meaning of olmSRLastCookieRcvd, it should
> be the best candidate for computing the synchronization status. However,
> this attribut is empty at OpenLDAP startup, so I can't really rely on it. Do
> anyone see other means to get the synchronization status?

I guess you could go that way, my approach[1] is to observe the cookies
directly (via syncrepl) where that of Howard's slapd-watcher[2] is to
read the contextCSN from the DB/syncprov.

As I usually mention in similar discussions, be wary of interpreting
short-lived large differences between CSNs as long replication delays,
you would emit many false positives.

[1]. https://git.openldap.org/openldap/syncmonitor
[2]. https://git.openldap.org/openldap/openldap/-/blob/master/tests/progs/slapd-watcher.c

**Comment by davidcoutadeur** [comment]
The provided tools seem interresting.
[1]: python code
[2]: C code, already available in tests/progs/ folder of OpenLDAP

Need more investigation to understand how [1] get the syncrepl status

For now, I propose to keep the current checksync function as is (doing ldapsearch on master directories)

**Comment by davidcoutadeur** [comment]
This can be re-evaluated for 2.6 OpenLDAP version

**Comment by davidcoutadeur** [comment]
Some update after testing a use case on 2.5.13 today:
- with olcLastBind set to TRUE, any authenticated ldapsearch on a directory makes an update of the contextCSN. This interfere with the verification of synchronization verification. Possible solution: make the contextCSN comparison tolerant (+/- 5s for example)
- it seems that slapcat does not always retrieve the last up to date contextCSN (sometimes > 5 minutes of difference). Possible solution: use rather ldapsearch for local search of contextCSN. It means searching for local server uri (in slapd-cli.conf), and using the same synchronization account as for masters

**Comment by davidcoutadeur** [comment]
https://git.openldap.org/openldap/openldap/-/blob/master/tests/progs/slapd-watcher.c is an interresting tool, but it cannot be used directly as a oneshot check of synchronization.

It provides statistics about:
- number of entries
- number of operations: bind, unbind, search, compare, modify, modDN, add, delete, abandon, extended
- contextCSN

contextCSN times are compared exactly. checks are done periodically (interval).

Example of command:
```
./slapd-watcher -x -D cn=syncrepl,dc=my-domain,dc=com -w secret -s1,2 -c dc=my-domain,dc=com -b dc=my-domain,dc=com ldaps://ldap1.domain.com:636 ldaps://ldap2.domain.com:636
```

Maybe it can be useful to include this binary in LTB packages, as a basic monitoring tool?

However, it cannot be used as a replacement solution for checksync target (ie a oneshot check that everything is synchronized)
