### ISSUE TITLE
Rename project to slapd-cli

### ISSUE THREAD

**Issue by coudot** [ltb-project/slapd-cli#22]
openldap-initscript is no more pertinent, we should rename this repository

**Comment by davidcoutadeur** [comment]
We must update documentation when we are about to release slapd-cli 2.8

Especially:
- renaming of the project
- slapd-cli targets
- deprecation of init.d
- deprecation of slurpd

See https://ltb-project.org/documentation, and especially:
- https://ltb-project.org/documentation/openldap-initscript
- https://ltb-project.org/documentation/nagios-plugins/check_ldap_slurpd_status
- https://ltb-project.org/documentation/nagios-plugins/check_berkeleydb_locks

**Comment by coudot** [comment]
Done
