### ISSUE TITLE
memberOf will be soon deprecated

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/slapd-cli#42]
It will be replaced by dynlist.

TODO:
- replace memberOf configuration by a dynlist (template configuration)
- provide a howto in documentation, explaining how to replace memberOf by dynlist?

**Comment by davidcoutadeur** [comment]
Done in 4e3c24c (use dynlist rather than memberOf in configuration templates)
I don't know if the howto is really usefull, we could just redirect users to the dynlist man page: https://www.openldap.org/software/man.cgi?query=slapo-dynlist

**Comment by meheni-ziani** [comment]
Hi David,

Thank you for this model, they will help me for my test with the overlay dynlist to replace Memberof.

Meheni

**Comment by davidcoutadeur** [comment]
One last remark: take care that dynlist can be much more time consuming while computing requests. (some rework is at stake by OpenLDAP core team)

**Comment by wwuck** [comment]
@davidcoutadeur it looks like `slapo-memberof` is no longer deprecated:

https://www.openldap.org/software/release/changes_lts.html

```
OpenLDAP 2.6.8 Release (2024/05/21)
	Documentation
		Fixed slapo-memberof is no longer deprecated (ITS#7400)
```

**Comment by davidcoutadeur** [comment]
Indeed, memberof is still a valid and useful overlay.

However, it is still provided as part of openldap-ltb packages, so nothing is to be done here. You can use either memberOf or dynlist, but take care using dynlist can take much more resources (time and cpu)
