### ISSUE TITLE
slapd-cli checksync fails with ERROR: no matching local contextCSN () found for remote, when startTLS is required

### ISSUE THREAD

**Issue by artlog** [ltb-project/slapd-cli#54]
slapd-cli checksync connects in ldap but does not support startTLS (-Z) option that would require addtionaly to have a valid hostname matching certificate :

slapd-cli checksync uses following request to get contextCSN 

```
/usr/local/openldap/bin/ldapsearch -x -H ldap://localhost:389 -D uid=syncrepl,ou=accounts,ou=infrastructure,dc=example,dc=com -w ... -b dc=example,dc=com -o nettimeout=5 -s base contextCSN
ldap_bind: Confidentiality required (13)
additional info: confidentiality required
```

It would require to use -Z and a correct hostname matching certificate subjectAltNames ( that could be mapped to 127.0.0.1 in /etc/hosts ).

**Comment by davidcoutadeur** [comment]
Indeed, it could be nice to have a new parameter in slapd-cli.conf:
```
LDAPSEARCH_OPTIONS=""
```

It could be empty by default, and if requiring starttls or other options (custom ldap.conf file for example), we could add them.

Note that `checksync` is not the only one to use `LDAPSEARCH_BIN`. There is also `version` action.

**Comment by davidcoutadeur** [comment]
Done in f940c1c
