### ISSUE TITLE
Possibility to delete older backup files

### ISSUE THREAD

**Issue by coudot** [ltb-project/slapd-cli#61]
When doing a backup we create a new file in the backup dir.

I would like to have the possibility to remove all previous backups older than X days, to avoid keeping them infinitely.

**Comment by davidcoutadeur** [comment]
Usually, we do that in a crontab. (a find command that searches backups older than X + rm)

But maybe could we add this feature inside LTB indeed.

**Comment by coudot** [comment]
Yes, it would avoid to write a backup script on top on slapd-cli. I'm looking at it.
