### ISSUE TITLE
Option to convert slapd.conf to cn=config at each startup

### ISSUE THREAD

**Issue by coudot** [ltb-project/slapd-cli#66]
Even if we share OpenLDAP developers opinion about getting rid of slapd.conf to only use cn=config, we have some administrators that are more comfortable with using slapd.conf.

One solution is to start slapd with `-f` to read slapd.conf instead of `-F` to read cn=config, which is already possible with slapd-cli

Another solution is to drop cn=config at startup and convert slapd.conf to cn=config, and then use `-F` to rely on cn=config. One use case can be to be able to temporally update configuration on the fly (for example to change loglevel), but keep maintaining the official configuration in slapd.conf.

**Comment by davidcoutadeur** [comment]
Done in #67
